# -*- coding: utf-8 -*-
"""data_augement

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/164k7xivlOF8KcKoOQIK-o1_x9k8QD3V8
"""

import cv2
import numpy as np
import os
import random

# ─────────────────────────────────────────
# 📂 폴더 경로 설정
# ─────────────────────────────────────────
# 원본 정예 사진을 넣을 폴더들 (이 폴더에 사진을 몇 장씩만 넣어두세요!)
INPUT_BASE_DIR = "dataset/original"
CLASSES = ["0_gray", "1_color", "2_mouse"]

# 증강된 사진들이 저장될 결과 폴더
OUTPUT_BASE_DIR = "dataset/augmented"

# 🎯 사진 1장당 만들 복사본 개수 (예: 30장씩 들어있으면 총 1,500장으로 뻥튀기됨)
AUGMENT_MULTIPLIER = 50


def create_folders():
    """필요한 폴더 구조 자동 생성"""
    for cls in CLASSES:
        os.makedirs(os.path.join(INPUT_BASE_DIR, cls), exist_ok=True)
        os.makedirs(os.path.join(OUTPUT_BASE_DIR, cls), exist_ok=True)


def random_shift(img, max_pixels=3):
    """상하좌우 미세 픽셀 밀림 재현 (최대 3픽셀)"""
    h, w = img.shape[:2]
    shift_x = random.randint(-max_pixels, max_pixels)
    shift_y = random.randint(-max_pixels, max_pixels)

    # 이동 행렬 생성
    M = np.float32([[1, 0, shift_x], [0, 1, shift_y]])
    # 외곽은 가장자리 색상으로 자연스럽게 채움
    return cv2.warpAffine(img, M, (w, h), borderMode=cv2.BORDER_REPLICATE)


def random_rotate(img, max_angle=3):
    """미세 회전 오차 재현 (최대 3도)"""
    h, w = img.shape[:2]
    angle = random.uniform(-max_angle, max_angle)
    center = (w // 2, h // 2)

    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    return cv2.warpAffine(img, M, (w, h), borderMode=cv2.BORDER_REPLICATE)


def random_brightness_contrast(img):
    """모니터 밝기 및 명암 변화 재현"""
    # 알파(명암): 0.85 ~ 1.15, 베타(밝기): -15 ~ 15
    alpha = random.uniform(0.85, 1.15)
    beta = random.randint(-15, 15)

    # 픽셀 값이 0~255를 벗어나지 않도록 클리핑 처리하며 연산
    return cv2.convertScaleAbs(img, alpha=alpha, beta=beta)


def main():
    create_folders()
    print("=" * 60)
    print("🪄  AI 훈련용 데이터 증강(Data Augmentation) 시스템 가동")
    print("=" * 60)
    print(f"ℹ️  원본 폴더 위치: {INPUT_BASE_DIR}")
    print(f"ℹ️  증강 폴더 위치: {OUTPUT_BASE_DIR}")
    print(f"ℹ️  배율 설정: 원본 사진 1장당 ➔ 변형본 {AUGMENT_MULTIPLIER}장 생성\n")

    total_generated = 0

    for cls in CLASSES:
        input_dir = os.path.join(INPUT_BASE_DIR, cls)
        output_dir = os.path.join(OUTPUT_BASE_DIR, cls)

        file_list = [f for f in os.listdir(input_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

        if not file_list:
            print(f"⚠️  [{cls}] 폴더에 원본 사진이 없습니다! 패스합니다.")
            continue

        print(f"📦 [{cls}] 수집된 원본 {len(file_list)}장 변형 시작...")

        generated_count = 0
        for filename in file_list:
            img_path = os.path.join(input_dir, filename)
            img = cv2.imread(img_path)

            if img is None: continue

            # 원본 파일명 추출 (.png 제거)
            base_name = os.path.splitext(filename)[0]

            # 설정한 개수만큼 미세하게 다른 변형본 생성
            for i in range(AUGMENT_MULTIPLIER):
                aug_img = img.copy()

                # 3가지 가상 변형 무작위 믹스 연산
                aug_img = random_shift(aug_img, max_pixels=2)
                aug_img = random_rotate(aug_img, max_angle=2)
                aug_img = random_brightness_contrast(aug_img)

                # 규격 통일화 (샴 네트워크 최적 입력 규격인 32x32로 일괄 리사이즈)
                aug_img = cv2.resize(aug_img, (32, 32), interpolation=cv2.INTER_AREA)

                # 새 파일명으로 저장
                out_filename = f"aug_{base_name}_{i}.png"
                cv2.imwrite(os.path.join(output_dir, out_filename), aug_img)
                generated_count += 1

        print(f"   ➔  🎉 변형 완료! 총 {generated_count}장의 데이터셋이 새로 구축되었습니다.")
        total_generated += generated_count

    print("\n" + "=" * 60)
    print(f"🎯 [최종 리포트] 데이터 뻥튀기 완료! 총 {total_generated}장 학습 준비 끝.")
    print("=" * 60)


if __name__ == "__main__":
    main()