# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNCyrqW9cKisKcFt-CggMAKvPsSWTKYL
"""

import os
import random
import numpy as np
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# ─────────────────────────────────────────
# ⚙️ 하이퍼파라미터 및 설정
# ─────────────────────────────────────────
DATA_DIR = "dataset/augmented"
BATCH_SIZE = 64
EPOCHS = 15
LEARNING_RATE = 0.001
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ─────────────────────────────────────────
# 📦 1. 샴 네트워크용 커스텀 데이터셋 정의
# ─────────────────────────────────────────
class SiameseDataset(Dataset):
    def __init__(self, data_dir):
        self.data_dir = data_dir
        self.classes = ["0_gray", "1_color", "2_mouse"]
        self.image_paths = []
        self.image_labels = []

        # 각 폴더별 이미지 경로 수집
        for idx, cls in enumerate(self.classes):
            cls_path = os.path.join(data_dir, cls)
            if not os.path.exists(cls_path): continue
            for filename in os.listdir(cls_path):
                if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
                    self.image_paths.append(os.path.join(cls_path, filename))
                    self.image_labels.append(idx)

        self.total_imgs = len(self.image_paths)
        if self.total_imgs == 0:
            raise ValueError(f"❌ '{data_dir}' 내부에 학습할 이미지가 없습니다!")

    def __len__(self):
        # 쌍(Pair) 기반 학습이므로 데이터 양을 넉넉히 잡습니다.
        return self.total_imgs * 2

    def __getitem__(self, index):
        # 50% 확률로 같은 클래스(Positive), 50% 확률로 다른 클래스(Negative) 쌍 생성
        should_get_same_class = random.randint(0, 1)

        # 첫 번째 이미지 무작위 선택
        idx1 = random.randint(0, self.total_imgs - 1)
        img1_path = self.image_paths[idx1]
        label1 = self.image_labels[idx1]

        if should_get_same_class:
            # 같은 클래스에서 두 번째 이미지 찾기
            while True:
                idx2 = random.randint(0, self.total_imgs - 1)
                if self.image_labels[idx2] == label1:
                    break
            target = 0.0  # 거리가 0이어야 함 (같음)
        else:
            # 다른 클래스에서 두 번째 이미지 찾기
            while True:
                idx2 = random.randint(0, self.total_imgs - 1)
                if self.image_labels[idx2] != label1:
                    break
            target = 1.0  # 거리가 1이어야 함 (다름)

        img2_path = self.image_paths[idx2]

        # 이미지 로드 및 전처리 (32x32 흑백 채널로 변환하여 노이즈 제거)
        img1 = cv2.imread(img1_path, cv2.IMREAD_GRAYSCALE)
        img2 = cv2.imread(img2_path, cv2.IMREAD_GRAYSCALE)

        # PyTorch 텐서 규격에 맞게 변환 (C, H, W) 및 정규화(0~1)
        img1_tensor = torch.tensor(img1, dtype=torch.float32).unsqueeze(0) / 255.0
        img2_tensor = torch.tensor(img2, dtype=torch.float32).unsqueeze(0) / 255.0
        target_tensor = torch.tensor(target, dtype=torch.float32)

        return img1_tensor, img2_tensor, target_tensor

# ─────────────────────────────────────────
# 🧠 2. 샴 네트워크 구조 설계 (CNN 신경망)
# ─────────────────────────────────────────
class SiameseNetwork(nn.Module):
    def __init__(self):
        super(SiameseNetwork, self).__init__()
        # 특징 추출기 (두 이미지가 공유하는 CNN 단추)
        self.cnn = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # 32x32 -> 16x16

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2, 2), # 16x16 -> 8x8

            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Flatten()
        )
        # 이미지를 16차원의 고유 특징 벡터 공간으로 압축
        self.fc = nn.Linear(64 * 8 * 8, 16)

    def forward_once(self, x):
        output = self.cnn(x)
        output = self.fc(output)
        return output

    def forward(self, input1, input2):
        # 두 영상을 각각 동일한 CNN 가중치로 통과시켜 특징 추출
        output1 = self.forward_once(input1)
        output2 = self.forward_once(input2)
        return output1, output2

# ─────────────────────────────────────────
# 📉 3. 대조 손실 함수 (Contrastive Loss) 정의
# ─────────────────────────────────────────
class ContrastiveLoss(nn.Module):
    def __init__(self, margin=1.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, output1, output2, label):
        # 유클리드 거리 계산
        euclidean_distance = nn.functional.pairwise_distance(output1, output2)
        # 같은 정답쌍(label=0)일 때 거리 최소화, 다른 정답쌍(label=1)일 때 마진만큼 멀어지게 함
        loss_contrastive = torch.mean(
            (1 - label) * torch.pow(euclidean_distance, 2) +
            (label) * torch.pow(torch.clamp(self.margin - euclidean_distance, min=0.0), 2)
        )
        return loss_contrastive

# ─────────────────────────────────────────
# 🚀 4. 메인 학습 루프
# ─────────────────────────────────────────
def main():
    print("="*60)
    print("🧠 티켓 매크로 연동형 샴 네트워크 AI 학습을 시작합니다.")
    print("="*60)
    print(f"📡 연산 장치: {DEVICE}")

    # 데이터 준비
    dataset = SiameseDataset(DATA_DIR)
    train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    # 네트워크, 손실함수, 옵티마이저 선언
    model = SiameseNetwork().to(DEVICE)
    criterion = ContrastiveLoss(margin=1.0)
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

    model.train()
    for epoch in range(EPOCHS):
        epoch_loss = 0.0
        for i, (img1, img2, label) in enumerate(train_loader):
            img1, img2, label = img1.to(DEVICE), img2.to(DEVICE), label.to(DEVICE)

            optimizer.zero_grad()
            out1, out2 = model(img1, img2)
            loss = criterion(out1, out2, label)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        avg_loss = epoch_loss / len(train_loader)
        print(f" Epoch [{epoch+1}/{EPOCHS}] ➔ 📉 에러율(Loss): {avg_loss:.4f}")

    # 💾 완성된 AI 뇌세포 파일로 저장
    os.makedirs("models", exist_ok=True)
    model_path = "models/siamese_ticket_model.pth"
    torch.save(model.state_dict(), model_path)
    print("\n" + "="*60)
    print(f"🎉 AI 학습 완벽 완료! 가중치 모델 파일이 저장되었습니다:")
    print(f" ➔ {model_path}")
    print("="*60)

if __name__ == "__main__":
    main()